
package com.founder.clpcecif.webservices.jyx.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProposalUndwrtServicePortType", targetNamespace = "http://service.proposalundwrt.dwx.commonship.webServiceCenter.sinosoft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProposalUndwrtServicePortType {


    /**
     * 
     * @param param0
     * @return
     *     returns com.founder.clpcecif.webservices.jyx.client.ProposalUndwrtResponse
     */
    @WebMethod(action = "urn:service")
    @WebResult(targetNamespace = "http://service.proposalundwrt.dwx.commonship.webServiceCenter.sinosoft.com")
    @RequestWrapper(localName = "service", targetNamespace = "http://service.proposalundwrt.dwx.commonship.webServiceCenter.sinosoft.com", className = "com.founder.clpcecif.webservices.jyx.client.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://service.proposalundwrt.dwx.commonship.webServiceCenter.sinosoft.com", className = "com.founder.clpcecif.webservices.jyx.client.ServiceResponse")
    public ProposalUndwrtResponse service(
        @WebParam(name = "param0", targetNamespace = "http://service.proposalundwrt.dwx.commonship.webServiceCenter.sinosoft.com")
        ProposalUndwrtRequest param0);

}
