
package com.base.webservices.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TestJdk6WebService", targetNamespace = "http://webservice.valens.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestJdk6WebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doService", targetNamespace = "http://webservice.valens.com/", className = "com.base.webservices.test.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://webservice.valens.com/", className = "com.base.webservices.test.DoServiceResponse")
    public String doService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doService2", targetNamespace = "http://webservice.valens.com/", className = "com.base.webservices.test.DoService2")
    @ResponseWrapper(localName = "doService2Response", targetNamespace = "http://webservice.valens.com/", className = "com.base.webservices.test.DoService2Response")
    public void doService2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
